# reference from settings (settings.yaml)
tavily_search: !SET ${templates.tools.tavily_search}

tool_node:
  initializer: tool_node
  data:
    tools:
      - '{{ tavily_search }}'
  
prompt:
  initializer: prompt_node
  data:
    template: 
      -
        - system
        - you are a helpful assistant, chat with a human with below history.
      -
        - placeholder
        - '{chat_history}'
      -
        - human
        - '{query}'

llm_with_tools:
  initializer: llm_node
  data:
    provider: openai # ollama
    tag: chat
    output_type: messages
    output_key: messages
    tools: '{{ tool_node }}'
    model: qwen-turbo # ollama3.2 # qwen2.5
    temperature: 0.3

chat_memory:
  initializer: chat_history
  data:
    provider: memory  

workflow_react:
  initializer: conditional_graph
  data:
    chat_history: '{{ chat_memory }}'
    history_input_key: query
    history_output_key: output
    output_mapping:   # map workflow outputs, default all fields
      output: output
      messages: messages
    inline:
      name: ReactWorkflow
      reset_state: true
      schema:
      - name: query  # input, required
        field_type: str
        required: true
      - name: output  # output, exposed to user
        field_type: str
        required: false
      # private, align with prompt, llm, and tools for nodes comunity
      - name: messages
        field_type: messages
        default: []
        operator: add
      - name: is_last_step  # schema field name
        field_type: bool
        default: false
      vertices:
      - name: prompt_node     # if using prompt node, better to parse the query instead of using `messages` from schema
        agent: '{{ prompt }}'
        next: llm_node
      - name: llm_node
        agent: '{{ llm_with_tools }}'
        next: branch_0
        output_mapping:
          messages: messages # map llm output to `messages`
          output: messages   # map llm output to `output`
      - name: branch_0
        default: __end__
        branchs:
        - conditions:
          # a trick to check if it's the end of workflow, tool calling wihout output
          - property: output
            value: ''
          next: tools_node
      - name: tools_node
        agent: '{{ tool_node }}'
        next: llm_node

# python cli.py -c workflow_react.yaml -i workflow_react -q "Trump's recent news?" -I query -O output